### ISSUE TITLE
EVE-NG _Docker Installation Issue_ Help Needed- Thanks

### ISSUE THREAD

**Issue by dlj2019** [breakintheweb/netshot#1]
Could you please help me to finish one of the last steps for EVE-NG by adding Docker to the Community Edition ? 
But i have no idea how to set the following instructions below:
![deepinscreenshot_select-area_20180315105049](https://user-images.githubusercontent.com/30886694/37471384-f1e85a1a-283f-11e8-8cde-1fb8e702f8ea.png)

I was able to add it by following the great instructions on your website below:

 http://breakintheweb.com/2017/08/27/EVE-NG-Docker/

Could you please help me out ?

Thanks in advance !

Regards,
DJ

**Comment by breakintheweb** [comment]
Please don't use the github issue system to post questions on unrelated topics. I no longer do any development on eve-ng and have been working on a different virtualization platform which will be opensource and include docker. You can find more info here if you are interested: www.qewig.com

**Comment by dlj2019** [comment]
Sure... I apologize for bothering you.

Thanks
